Vagrant::Config.run do |config|
	config.vm.box = "lucid32"
	config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
	# config.vm.boot_mode = :gui

	config.vm.customize do |vm|
	    vm.name = "nodebox"
	end
	
	config.vm.forward_port(80, 8888)
	config.vm.share_folder("dev", "/home/vagrant/source", "/data/development/source")	

	config.vm.provision :puppet, :options => ["--user", "root"]
end
